# eza's colours, from themes/{{ name }}/colors.toml. Sourced by ~/.zshrc.
# Generated by hypora-theme — edit the template, not this file.
#
# Truecolor (38;2;R;G;B) rather than the 16 ANSI slots, so the listing uses the theme's own
# palette rather than whatever the terminal happens to map `yellow` to. That matters for the
# colours with no ANSI slot at all: `dim` for the permission dashes, `accent` for directories.
#
# The scheme follows eza's own semantics — colour by meaning, not by file type alone — so a
# listing reads as columns: what it is, how big, whose, when, and what it's called.
# Key reference: `man 5 eza_colors`.
export EZA_COLORS="\
hd=4;38;2;{{ foreground_rgb }}:\
di=1;38;2;{{ accent_rgb }}:\
fi=38;2;{{ foreground_rgb }}:\
ex=1;38;2;{{ green_rgb }}:\
ln=38;2;{{ cyan_rgb }}:\
or=3;38;2;{{ error_rgb }}:\
ur=38;2;{{ yellow_rgb }}:\
uw=38;2;{{ red_rgb }}:\
ux=38;2;{{ green_rgb }}:\
ue=38;2;{{ green_rgb }}:\
gr=38;2;{{ yellow_rgb }}:\
gw=38;2;{{ red_rgb }}:\
gx=38;2;{{ green_rgb }}:\
tr=38;2;{{ yellow_rgb }}:\
tw=38;2;{{ red_rgb }}:\
tx=38;2;{{ green_rgb }}:\
su=38;2;{{ magenta_rgb }}:\
sf=38;2;{{ magenta_rgb }}:\
xa=38;2;{{ dim_rgb }}:\
sn=38;2;{{ green_rgb }}:\
sb=38;2;{{ green_rgb }}:\
uu=1;38;2;{{ yellow_rgb }}:\
un=38;2;{{ dim_rgb }}:\
gu=38;2;{{ dim_rgb }}:\
gn=38;2;{{ dim_rgb }}:\
lc=38;2;{{ dim_rgb }}:\
da=38;2;{{ blue_rgb }}:\
in=38;2;{{ dim_rgb }}:\
bl=38;2;{{ dim_rgb }}:\
xx=38;2;{{ dim_rgb }}:\
ga=38;2;{{ green_rgb }}:\
gm=38;2;{{ yellow_rgb }}:\
gd=38;2;{{ red_rgb }}:\
gv=38;2;{{ magenta_rgb }}:\
gt=38;2;{{ cyan_rgb }}:\
gi=38;2;{{ dim_rgb }}:\
gc=38;2;{{ error_rgb }}:\
"
