# Generated by hypora-theme ({{ name }}). Used as gtk-3.0/settings.ini and gtk-4.0/settings.ini.
[Settings]
gtk-theme-name={{ gtk_theme }}
gtk-icon-theme-name={{ icon_theme }}
gtk-font-name=Liberation Sans 11
gtk-application-prefer-dark-theme={{ prefer_dark }}
