/* Generated by hypora-theme ({{ name }}). Loaded by GTK 4 / libadwaita apps and by GTK 3
   apps using adw-gtk3, which understands the same color names. */
@define-color accent_color {{ accent }};
@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ background }};
@define-color destructive_color {{ error }};
@define-color destructive_bg_color {{ error }};
@define-color destructive_fg_color {{ background }};
@define-color success_color {{ green }};
@define-color success_bg_color {{ green }};
@define-color success_fg_color {{ background }};
@define-color warning_color {{ yellow }};
@define-color warning_bg_color {{ yellow }};
@define-color warning_fg_color {{ background }};
@define-color error_color {{ error }};
@define-color error_bg_color {{ error }};
@define-color error_fg_color {{ background }};

@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};
@define-color view_bg_color {{ background }};
@define-color view_fg_color {{ foreground }};
@define-color headerbar_bg_color {{ surface }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_border_color {{ muted }};
@define-color headerbar_backdrop_color {{ background }};
@define-color sidebar_bg_color {{ surface }};
@define-color sidebar_fg_color {{ foreground }};
@define-color sidebar_backdrop_color {{ surface }};
@define-color secondary_sidebar_bg_color {{ surface }};
@define-color secondary_sidebar_fg_color {{ foreground }};
@define-color card_bg_color {{ surface }};
@define-color card_fg_color {{ foreground }};
@define-color dialog_bg_color {{ surface }};
@define-color dialog_fg_color {{ foreground }};
@define-color popover_bg_color {{ surface }};
@define-color popover_fg_color {{ foreground }};
@define-color thumbnail_bg_color {{ surface }};
@define-color thumbnail_fg_color {{ foreground }};

/* libadwaita 1.6+ reads CSS variables */
:root {
    --accent-color: {{ accent }};
    --accent-bg-color: {{ accent }};
    --accent-fg-color: {{ background }};
    --destructive-bg-color: {{ error }};
    --window-bg-color: {{ background }};
    --window-fg-color: {{ foreground }};
    --view-bg-color: {{ background }};
    --view-fg-color: {{ foreground }};
    --headerbar-bg-color: {{ surface }};
    --headerbar-fg-color: {{ foreground }};
    --sidebar-bg-color: {{ surface }};
    --sidebar-fg-color: {{ foreground }};
    --card-bg-color: {{ surface }};
    --card-fg-color: {{ foreground }};
    --dialog-bg-color: {{ surface }};
    --dialog-fg-color: {{ foreground }};
    --popover-bg-color: {{ surface }};
    --popover-fg-color: {{ foreground }};
}
