# Generated by hypora-theme ({{ name }}). Lock screen (SUPER + L or the Lock button).
general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba({{ background_hex }}ff)
}

label {
    monitor =
    text = $TIME
    color = rgba({{ foreground_hex }}ff)
    font_size = 88
    font_family = {{ font }}
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %-d"
    color = rgba({{ accent_hex }}ff)
    font_size = 18
    font_family = {{ font }}
    position = 0, 70
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 360, 50
    outline_thickness = 2
    rounding = -1
    dots_size = 0.22
    dots_spacing = 0.45
    outer_color = rgba({{ accent_hex }}ff)
    inner_color = rgba({{ surface_hex }}ff)
    font_color = rgba({{ foreground_hex }}ff)
    check_color = rgba({{ yellow_hex }}ff)
    fail_color = rgba({{ error_hex }}ff)
    fail_text = $FAIL
    fade_on_empty = false
    placeholder_text = Password
    font_family = {{ font }}
    position = 0, -30
    halign = center
    valign = center
}
