-- Generated by hypora-theme ({{ name }}). Loaded from ~/.config/hypr/hyprland.lua.
hl.config({
    general = {
        col = {
            active_border   = { colors = { "rgba({{ accent_hex }}ee)", "rgba({{ magenta_hex }}ee)" }, angle = 45 },
            inactive_border = "rgba({{ muted_hex }}aa)",
        },
    },
})
