# Generated by hypora-theme ({{ name }}). Included from ~/.config/kitty/kitty.conf.
foreground {{ term_foreground }}
background {{ background }}
selection_foreground {{ term_foreground }}
selection_background {{ selection }}
url_color {{ cyan }}

cursor {{ foreground }}
cursor_text_color {{ background }}

active_border_color {{ accent }}
inactive_border_color {{ muted }}
active_tab_foreground {{ background }}
active_tab_background {{ accent }}
inactive_tab_foreground {{ dim }}
inactive_tab_background {{ surface }}
tab_bar_background {{ background }}

color0 {{ black }}
color1 {{ red }}
color2 {{ green }}
color3 {{ yellow }}
color4 {{ blue }}
color5 {{ magenta }}
color6 {{ cyan }}
color7 {{ white }}
color8 {{ bright_black }}
color9 {{ bright_red }}
color10 {{ bright_green }}
color11 {{ bright_yellow }}
color12 {{ bright_blue }}
color13 {{ bright_magenta }}
color14 {{ bright_cyan }}
color15 {{ bright_white }}
