# Generated by hypora-theme from themes/{{ name }}/colors.toml. Don't edit: change the
# palette (or themes/templates/plymouth.plymouth.tpl) and run hypora-theme again.
#
# The boot screen, including the LUKS passphrase prompt. Installed to
# /usr/share/plymouth/themes/hypora/hypora.plymouth and copied into the initramfs by dracut,
# so changes here only reach the screen after `sudo dracut -f`.
#
# The two-step module below is the one Fedora's own themes are built on. It takes these
# colours from this file; everything else on screen is a PNG from the image directory, which
# hypora-plymouth draws in the same palette. One thing it does NOT expose is the colour of
# the prompt text, which it always draws white — fine for a dark palette, wrong for a light.
#
# Careful with comments here. plymouth-set-default-theme and plymouth-populate-initrd pull
# values out of this file with unanchored greps and expand them unquoted, so a comment that
# happens to contain one of their key names followed by '=' matches too. The value then
# becomes two lines, and `[ ! -e $VALUE.so ]` dies with "too many arguments" — after which
# the module is silently left out of the initramfs and the boot screen falls back to text.
# Keys that bite: ModuleName and ImageDir (no guard at all), Font, TitleFont and
# MonospaceFont (first match wins, so a comment above the real line would shadow it).
#
# plymouth-populate-initrd runs fc-match on Font and TitleFont and copies the matching font
# file into the initramfs, so naming a font here is all that's needed to use it at boot.
[Plymouth Theme]
Name=Hypora
Description=Hypora boot screen, in the {{ name }} palette
ModuleName=two-step

[two-step]
ImageDir=/usr/share/plymouth/themes/hypora
Font={{ font }} 12
TitleFont={{ font }} 22

BackgroundStartColor=0x{{ background_hex }}
BackgroundEndColor=0x{{ background_hex }}
ProgressBarBackgroundColor=0x{{ surface_hex }}
ProgressBarForegroundColor=0x{{ accent_hex }}
ProgressBarWidth=320
ProgressBarHeight=4
ProgressBarHorizontalAlignment=.5
ProgressBarVerticalAlignment=.75

DialogHorizontalAlignment=.5
DialogVerticalAlignment=.45
TitleHorizontalAlignment=.5
TitleVerticalAlignment=.382
HorizontalAlignment=.5
VerticalAlignment=.75
WatermarkHorizontalAlignment=.5
WatermarkVerticalAlignment=.92

Transition=none
TransitionDuration=0.0
MessageBelowAnimation=true
# Without this the firmware's own logo stays behind the dialog and the palette background
# never shows; Fedora's bgrt theme leaves it on deliberately, Hypora does not.
DialogClearsFirmwareBackground=true

[boot-up]
UseFirmwareBackground=false
UseEndAnimation=false
UseProgressBar=true

[shutdown]
UseFirmwareBackground=false
UseEndAnimation=false
UseProgressBar=true

[reboot]
UseFirmwareBackground=false
UseEndAnimation=false
UseProgressBar=true

[updates]
SuppressMessages=true
ProgressBarShowPercentComplete=true
UseProgressBar=true
Title=Installing Updates...
SubTitle=Do not turn off your computer

[system-upgrade]
SuppressMessages=true
ProgressBarShowPercentComplete=true
UseProgressBar=true
Title=Upgrading System...
SubTitle=Do not turn off your computer

[firmware-upgrade]
SuppressMessages=true
ProgressBarShowPercentComplete=true
UseProgressBar=true
Title=Upgrading Firmware...
SubTitle=Do not turn off your computer

[system-reset]
SuppressMessages=true
ProgressBarShowPercentComplete=true
UseProgressBar=true
Title=Resetting System...
SubTitle=Do not turn off your computer
