# Generated by hypora-theme ({{ name }}). Qt apps use it via QT_QPA_PLATFORMTHEME=qt6ct.
[Appearance]
style=Fusion
custom_palette=true
color_scheme_path={{ home }}/.config/hypora/current/qt6ct-colors.conf
icon_theme={{ icon_theme }}
standard_dialogs=default

[Fonts]
fixed="{{ font }},11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Liberation Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
