[General]
# Generated by hypora-theme ({{ name }}). Installed to /usr/share/sddm/themes/hypora/theme.conf.
bg="{{ background }}"
surface="{{ surface }}"
fg="{{ foreground }}"
dim="{{ dim }}"
accent="{{ accent }}"
error="{{ error }}"
font="{{ font }}"
