pragma Singleton
import Quickshell
import QtQuick

// Generated by hypora-theme from themes/{{ name }}/colors.toml. Don't edit: change the
// palette (or themes/templates/Theme.qml.tpl) and run hypora-theme again.
Singleton {
    readonly property string name: "{{ name }}"

    readonly property color bg: "{{ background }}"
    readonly property color surface: "{{ surface }}"
    readonly property color fg: "{{ foreground }}"
    readonly property color dim: "{{ dim }}"
    readonly property color accent: "{{ accent }}"
    readonly property color error: "{{ error }}"
    readonly property color warn: "{{ yellow }}"
    readonly property string font: "{{ font }}"
    readonly property int fontSize: 13

    // Apps launched from widget clicks. The last three are commands run in the terminal,
    // reached from the Network and Bluetooth windows under "Advanced".
    readonly property string terminal: "kitty"
    readonly property string mixer: "wiremix"
    readonly property string network: "nmtui"
    readonly property string bluetooth: "bluetoothctl"
}
